repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.105.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
  #Trivy
  - repo: local
    hooks:
      - id: trivy
        name: trivy
        entry: trivy fs --scanners=vuln,secret,misconfig --severity=CRITICAL,HIGH --skip-dirs=.terraform ./
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks

